version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-authorization-token --region us-east-2
      - REPOSITORY_URI=363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - docker build -t repoprova-matheus:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag repoprova-matheus:$CODEBUILD_RESOLVED_SOURCE_VERSION 363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - docker push 363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus:$CODEBUILD_RESOLVED_SOURCE_VERSION
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
