version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-authorization-token --region us-east-2
      - REPOSITORY_URI=363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus
  build:
    commands:
      - docker build -t repoprova-matheus .
      - docker tag repoprova-matheus:v1 363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus:v1
  post_build:
    commands:
      - docker push 363838752048.dkr.ecr.us-east-2.amazonaws.com/repoprova-matheus:v1
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
